# Redcarpet is a Markdown processor
#it's the thing that converts Markdown to HTML
#GitHub uses Redcarpet for conversion so we want to remain consistent
markdown: redcarpet
#The folder our website is hosted in
#Eeverything that comems after http://leekh91kr.github.io
baseurl: /dinosaurs
